<option value="Karyawan">Karyawan</option>
<option value="PNS">PNS</option>
<option value="Ibu Rumah Tangga">Ibu Rumah Tangga</option>
<option value="Pelajar/Mahasiswa">Pelajar/Mahasiswa</option>
<option value="Pelaut">Pelaut</option>
<option value="ABRI">ABRI</option>
<option value="Dokter">Dokter</option>
<option value="Guru">Guru</option>
<option value="Pengacara">Pengacara</option>
<option value="Wiraswasta">Wiraswasta</option>
<option value="Tidak Bekerja">Tidak Bekerja</option>